# This is a basic workflow to help you get started with Actions

name: TroopCalculator

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs:
        leadership:
           description: 'Total leadership of your attack'
           required: true
        battle-plan:
           type: choice
           description: 'The kill order from left to right'
           options:
           - S8:S9:G8:G9:MELEE:MOUNT:RANGE:FLY
           - S8:S9:G8:G9:MELEE:FLY:MOUNT:RANGE
           
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          python troopCalc.py ${{ github.event.inputs.leadership }} ${{ github.event.inputs.battle-plan }} >> $GITHUB_STEP_SUMMARY
